### ISSUE TITLE
Using Python 2 by mistake; uninstalling and fixing

### ISSUE THREAD

**Issue by yuanagain** [anned20/begoneads#3]
Hi! I accidentally ran `setup.py` with Python 2. When I try to run `begoneads` I get an error (see below). I suspect the issue has to do with `begoneads` trying to use Python 2. How can I point it to Python 3?

Thanks,

Yuan

```
Traceback (most recent call last):
  File "/usr/local/bin/begoneads", line 11, in <module>
    load_entry_point('begoneads==0.0.6', 'console_scripts', 'begoneads')()
  File "/Users/yuanwang/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/yuanwang/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/yuanwang/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/yuanwang/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/begoneads-0.0.6-py2.7.egg/begoneads/begoneads.py", line 7, in <module>
    from begoneads.collectors.remote_collector import RemoteCollector
ImportError: No module named collectors.remote_collector
```

**Comment by anned20** [comment]
Hi Yuan!

The best fix would be to completely remove the folder `/usr/local/lib/python2.7/site-packages/begoneads-0.0.6-py2.7.egg`.
This will delete BeGoneAds from your system and then you can install it with `python3 setup.py install`

Cheers,
Anne Douwe
