### ISSUE TITLE
Various SyntaxErrors on install

### ISSUE THREAD

**Issue by mikemaccana** [anned20/begoneads#4]
Note this is Windows 10:

```
~\Code\begoneads $ python setup.py install
running install
running bdist_egg
running egg_info
creating begoneads.egg-info
writing requirements to begoneads.egg-info\requires.txt
writing begoneads.egg-info\PKG-INFO
writing top-level names to begoneads.egg-info\top_level.txt
writing dependency_links to begoneads.egg-info\dependency_links.txt
writing entry points to begoneads.egg-info\entry_points.txt
writing manifest file 'begoneads.egg-info\SOURCES.txt'
reading manifest file 'begoneads.egg-info\SOURCES.txt'
writing manifest file 'begoneads.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\begoneads
copying begoneads\begoneads.py -> build\lib\begoneads
copying begoneads\exceptions.py -> build\lib\begoneads
copying begoneads\helpers.py -> build\lib\begoneads
copying begoneads\hostsmanager.py -> build\lib\begoneads
copying begoneads\hostsmanager_test.py -> build\lib\begoneads
copying begoneads\__init__.py -> build\lib\begoneads
creating build\lib\begoneads\collectors
copying begoneads\collectors\base_collector.py -> build\lib\begoneads\collectors
copying begoneads\collectors\local_collector.py -> build\lib\begoneads\collectors
copying begoneads\collectors\remote_collector.py -> build\lib\begoneads\collectors
copying begoneads\collectors\remote_collector_test.py -> build\lib\begoneads\collectors
copying begoneads\collectors\__init__.py -> build\lib\begoneads\collectors
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\begoneads
copying build\lib\begoneads\begoneads.py -> build\bdist.win-amd64\egg\begoneads
creating build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\collectors\base_collector.py -> build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\collectors\local_collector.py -> build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\collectors\remote_collector.py -> build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\collectors\remote_collector_test.py -> build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\collectors\__init__.py -> build\bdist.win-amd64\egg\begoneads\collectors
copying build\lib\begoneads\exceptions.py -> build\bdist.win-amd64\egg\begoneads
copying build\lib\begoneads\helpers.py -> build\bdist.win-amd64\egg\begoneads
copying build\lib\begoneads\hostsmanager.py -> build\bdist.win-amd64\egg\begoneads
copying build\lib\begoneads\hostsmanager_test.py -> build\bdist.win-amd64\egg\begoneads
copying build\lib\begoneads\__init__.py -> build\bdist.win-amd64\egg\begoneads
byte-compiling build\bdist.win-amd64\egg\begoneads\begoneads.py to begoneads.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\collectors\base_collector.py to base_collector.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\collectors\local_collector.py to local_collector.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\collectors\remote_collector.py to remote_collector.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\collectors\remote_collector_test.py to remote_collector_test.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\collectors\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\exceptions.py to exceptions.pyc
  File "build\bdist.win-amd64\egg\begoneads\exceptions.py", line 7
    self.message = f'{source} is not a valid source'
                                                   ^
SyntaxError: invalid syntax

byte-compiling build\bdist.win-amd64\egg\begoneads\helpers.py to helpers.pyc
byte-compiling build\bdist.win-amd64\egg\begoneads\hostsmanager.py to hostsmanager.pyc
  File "build\bdist.win-amd64\egg\begoneads\hostsmanager.py", line 6
    pattern = re.compile(f'(?<={start_marker})(.*)(?={end_marker})',
                                                                  ^
SyntaxError: invalid syntax

byte-compiling build\bdist.win-amd64\egg\begoneads\hostsmanager_test.py to hostsmanager_test.pyc
  File "build\bdist.win-amd64\egg\begoneads\hostsmanager_test.py", line 16
    with_begoneads = f'''
127.0.0.1 localhost whatever-hostname
0.0.0.0 some.local

{start_marker}
0.0.0.0 inserted.by.begoneads
{end_marker}
'''







  ^
SyntaxError: invalid syntax

byte-compiling build\bdist.win-amd64\egg\begoneads\__init__.py to __init__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying begoneads.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\begoneads-0.0.6-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing begoneads-0.0.6-py2.7.egg
creating c:\python27\lib\site-packages\begoneads-0.0.6-py2.7.egg
Extracting begoneads-0.0.6-py2.7.egg to c:\python27\lib\site-packages
  File "c:\python27\lib\site-packages\begoneads-0.0.6-py2.7.egg\begoneads\exceptions.py", line 7
    self.message = f'{source} is not a valid source'
                                                   ^
SyntaxError: invalid syntax

  File "c:\python27\lib\site-packages\begoneads-0.0.6-py2.7.egg\begoneads\hostsmanager.py", line 6
    pattern = re.compile(f'(?<={start_marker})(.*)(?={end_marker})',
                                                                  ^
SyntaxError: invalid syntax

  File "c:\python27\lib\site-packages\begoneads-0.0.6-py2.7.egg\begoneads\hostsmanager_test.py", line 16
    with_begoneads = f'''
127.0.0.1 localhost whatever-hostname
0.0.0.0 some.local

{start_marker}
0.0.0.0 inserted.by.begoneads
{end_marker}
'''







  ^
SyntaxError: invalid syntax

Adding begoneads 0.0.6 to easy-install.pth file
Installing begoneads-script.py script to C:\Python27\Scripts
Installing begoneads.exe script to C:\Python27\Scripts

Installed c:\python27\lib\site-packages\begoneads-0.0.6-py2.7.egg
Processing dependencies for begoneads==0.0.6
Searching for tqdm
Reading https://pypi.org/simple/tqdm/
Downloading https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl#sha256=e288416eecd4df19d12407d0c913cbf77aa8009d7fddb18f632aded3bdbdda6b
Best match: tqdm 4.32.1
Processing tqdm-4.32.1-py2.py3-none-any.whl
Installing tqdm-4.32.1-py2.py3-none-any.whl to c:\python27\lib\site-packages
writing requirements to c:\python27\lib\site-packages\tqdm-4.32.1-py2.7.egg\EGG-INFO\requires.txt
Adding tqdm 4.32.1 to easy-install.pth file
Installing tqdm-script.py script to C:\Python27\Scripts
Installing tqdm.exe script to C:\Python27\Scripts

Installed c:\python27\lib\site-packages\tqdm-4.32.1-py2.7.egg
Searching for requests
Reading https://pypi.org/simple/requests/
Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl#sha256=9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
Best match: requests 2.22.0
Processing requests-2.22.0-py2.py3-none-any.whl
Installing requests-2.22.0-py2.py3-none-any.whl to c:\python27\lib\site-packages
writing requirements to c:\python27\lib\site-packages\requests-2.22.0-py2.7.egg\EGG-INFO\requires.txt
Adding requests 2.22.0 to easy-install.pth file

Installed c:\python27\lib\site-packages\requests-2.22.0-py2.7.egg
Searching for click
Reading https://pypi.org/simple/click/
Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl#sha256=2335065e6395b9e67ca716de5f7526736bfa6ceead690adf616d925bdc622b13
Best match: Click 7.0
Processing Click-7.0-py2.py3-none-any.whl
Installing Click-7.0-py2.py3-none-any.whl to c:\python27\lib\site-packages
Adding Click 7.0 to easy-install.pth file

Installed c:\python27\lib\site-packages\click-7.0-py2.7.egg
Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl#sha256=b246607a25ac80bedac05c6f282e3cdaf3afb65420fd024ac94435cabe6e18d1
Best match: urllib3 1.25.3
Processing urllib3-1.25.3-py2.py3-none-any.whl
Installing urllib3-1.25.3-py2.py3-none-any.whl to c:\python27\lib\site-packages
writing requirements to c:\python27\lib\site-packages\urllib3-1.25.3-py2.7.egg\EGG-INFO\requires.txt
Adding urllib3 1.25.3 to easy-install.pth file

Installed c:\python27\lib\site-packages\urllib3-1.25.3-py2.7.egg
Searching for idna<2.9,>=2.5
Reading https://pypi.org/simple/idna/
Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl#sha256=ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c
Best match: idna 2.8
Processing idna-2.8-py2.py3-none-any.whl
Installing idna-2.8-py2.py3-none-any.whl to c:\python27\lib\site-packages
Adding idna 2.8 to easy-install.pth file

Installed c:\python27\lib\site-packages\idna-2.8-py2.7.egg
Searching for chardet<3.1.0,>=3.0.2
Reading https://pypi.org/simple/chardet/
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl#sha256=fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691
Best match: chardet 3.0.4
Processing chardet-3.0.4-py2.py3-none-any.whl
Installing chardet-3.0.4-py2.py3-none-any.whl to c:\python27\lib\site-packages
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect-script.py script to C:\Python27\Scripts
Installing chardetect.exe script to C:\Python27\Scripts

Installed c:\python27\lib\site-packages\chardet-3.0.4-py2.7.egg
Searching for certifi>=2017.4.17
Reading https://pypi.org/simple/certifi/
Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl#sha256=59b7658e26ca9c7339e00f8f4636cdfe59d34fa37b9b04f6f9e9926b3cece1a5
Best match: certifi 2019.3.9
Processing certifi-2019.3.9-py2.py3-none-any.whl
Installing certifi-2019.3.9-py2.py3-none-any.whl to c:\python27\lib\site-packages
Adding certifi 2019.3.9 to easy-install.pth file

Installed c:\python27\lib\site-packages\certifi-2019.3.9-py2.7.egg
Finished processing dependencies for begoneads==0.0.6
~\Code\begoneads $ python setup.py installbegoneads^C
~\Code\begoneads $ begoneads
Traceback (most recent call last):
  File "C:\Python27\Scripts\begoneads-script.py", line 11, in <module>
    load_entry_point('begoneads==0.0.6', 'console_scripts', 'begoneads')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\begoneads-0.0.6-py2.7.egg\begoneads\begoneads.py", line 7, in <module>
    from begoneads.collectors.remote_collector import RemoteCollector
ImportError: No module named collectors.remote_collector
~\Code\begoneads $
```

**Comment by anned20** [comment]
Hi Mike!

If I see it correctly, you're using Python 2.7, you need to use 3.6 or higher for BeGoneAds

Cheers,
Anne Douwe

**Comment by mikemaccana** [comment]
You're right. Could the script check for the Python version and exit?

**Comment by anned20** [comment]
I added this for the v0.0.7 milestone, thanks for this issue!
